Update FreeBSD build manifest

diff --git a/.builds/freebsd.yml b/.builds/freebsd.yml
--- a/.builds/freebsd.yml
+++ b/.builds/freebsd.yml
@@ -18,6 +18,24 @@ tasks:
       cd kefir
       gmake clean clean_bootstrap
       gmake all PROFILE=reldebug CC=clang
+  - lua_tests: |
+      cd kefir
+      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/bin/libs
+      export LC_ALL=C.UTF-8
+      export KEFIR_RTLIB="$HOME/kefir/bin/libs/libkefirrt.a"
+      export KEFIR_RTINC="$HOME/kefir/headers/kefir/runtime"
+      export KEFIR_CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1"
+      ./source/tests/misc/run-lua-tests.sh "$(pwd)/bin/kefir" "$(pwd)/bin/lua-test"
+  - c_testsuite: |
+      cd c-testsuite
+      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/kefir/bin/libs
+      export KEFIRCC="$HOME/kefir/bin/kefir"
+      export KEFIR_RTLIB="$HOME/kefir/bin/libs/libkefirrt.a"
+      export KEFIR_RTINC="$HOME/kefir/headers/kefir/runtime"
+      export CFLAGS="-O1 -fPIC -pie -D__GNUC__=4 -D__GNUC_MINOR__=20 -D__GNUC_STDC_INLINE__=1"
+      export LC_ALL=C.UTF-8 
+      ./single-exec kefir | tee ~/c-tests.log
+      [[ "x$(cat ~/c-tests.log | scripts/tapsummary | grep 'fail 0' | wc -l | tr -d ' ')" == "x1" ]] || exit 1
   - gcc_torture: |
       wget ftp://ftp.gnu.org/gnu/gcc/gcc-13.1.0/gcc-13.1.0.tar.xz
       tar xvf gcc-13.1.0.tar.xz
